{
 "title": "Full Metric",
 "tags": [
  "aws",
  "performance test"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-baseline-alb/ac44ea25d8fb0d47"
     },
     "label": "Baseline",
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\"",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-scale-alb/6ee98ab41ff4d7c9"
     },
     "label": "Scale",
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/auto-benchmark-scale-alb/0e25670bf4ee5f90"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/auto-benchmark-scale-alb/0e25670bf4ee5f90'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-redis-alb/d03e53e8e9d73b0a"
     },
     "label": "Redis",
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\"",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-kafka-alb/bde1e9d346d9c129"
     },
     "label": "Kafka",
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\"",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target Response Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-baseline-alb/ac44ea25d8fb0d47"
     },
     "label": "Baseline",
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\"",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-scale-alb/6ee98ab41ff4d7c9"
     },
     "label": "Scale",
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/auto-benchmark-scale-alb/0e25670bf4ee5f90"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/auto-benchmark-scale-alb/0e25670bf4ee5f90'",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-redis-alb/d03e53e8e9d73b0a"
     },
     "label": "Redis",
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\"",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-kafka-alb/bde1e9d346d9c129"
     },
     "label": "Kafka",
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_2XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_2XX_Count) FROM \"AWS/ApplicationELB\"",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ELB 5XX Error",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-baseline-alb/ac44ea25d8fb0d47"
     },
     "label": "Baseline",
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/auto-benchmark-baseline-alb/70ecab52f3df5e7b"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/auto-benchmark-baseline-alb/70ecab52f3df5e7b'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-scale-alb/6ee98ab41ff4d7c9"
     },
     "label": "Scale",
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "COUNT",
       "parameters": [
        { "name": "HTTPCode_ELB_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/auto-benchmark-scale-alb/0e25670bf4ee5f90"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT COUNT(HTTPCode_ELB_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/auto-benchmark-scale-alb/0e25670bf4ee5f90'",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-redis-alb/d03e53e8e9d73b0a"
     },
     "label": "Redis",
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-kafka-alb/bde1e9d346d9c129"
     },
     "label": "Kafka",
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/ApplicationELB", "type": "string" }, "type": "property" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "HTTPCode_Target_5XX_Count", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "app/auto-benchmark-kafka-alb/7d68fb2aff3cf022"
         },
         "property": { "name": "LoadBalancer", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(HTTPCode_Target_5XX_Count) FROM \"AWS/ApplicationELB\" WHERE LoadBalancer = 'app/auto-benchmark-kafka-alb/7d68fb2aff3cf022'",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Target 5XX Error",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-baseline-alb/ac44ea25d8fb0d47"
     },
     "label": "Baseline",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-scale-alb/6ee98ab41ff4d7c9"
     },
     "label": "Scale\r\n",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-redis-alb/d03e53e8e9d73b0a"
     },
     "label": "Redis",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "LoadBalancer": "app/auto-benchmark-kafka-alb/bde1e9d346d9c129"
     },
     "label": "Kafka",
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "ECS Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Task Count - FastAPI",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "auto-benchmark-baseline-cluster",
      "ServiceName": "auto-benchmark-baseline-service-fastapi"
     },
     "label": "Baseline",
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "ECS/ContainerInsights", "type": "string" }, "type": "property" },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DesiredTaskCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        {
         "operator": {
          "name": "=",
          "value": "auto-benchmark-baseline-cluster"
         },
         "property": { "name": "ClusterName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DesiredTaskCount) FROM \"ECS/ContainerInsights\" WHERE ClusterName = 'auto-benchmark-baseline-cluster' ORDER BY SUM() ASC",
     "statistic": "Sum"
    },
    {
     "label": "Scale",
     "metricName": "DesiredTaskCount",
     "metricQueryType": 1,
     "namespace": "ECS/ContainerInsights",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "ECS/ContainerInsights", "type": "string" }, "type": "property" },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DesiredTaskCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "auto-benchmark-scale-cluster" }, "property": { "name": "ClusterName", "type": "string" }, "type": "operator" },
        {
         "operator": {
          "name": "=",
          "value": "auto-benchmark-scale-service-fastapi"
         },
         "property": { "name": "ServiceName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DesiredTaskCount) FROM \"ECS/ContainerInsights\" WHERE ClusterName = 'auto-benchmark-scale-cluster' AND ServiceName = 'auto-benchmark-scale-service-fastapi' ORDER BY SUM() ASC",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "auto-benchmark-redis-cluster",
      "ServiceName": "auto-benchmark-redis-service-fastapi"
     },
     "label": "Redis",
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": {
      "ClusterName": "auto-benchmark-kafka-cluster",
      "ServiceName": "auto-benchmark-kafka-service-fastapi"
     },
     "label": "Kafka",
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CPU Utilization(%) - FastAPI",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "auto-benchmark-baseline-cluster",
      "ServiceName": "auto-benchmark-baseline-service-fastapi"
     },
     "label": "Baseline",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "auto-benchmark-scale-cluster",
      "ServiceName": "auto-benchmark-scale-service-fastapi"
     },
     "label": "Scale",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "auto-benchmark-redis-cluster",
      "ServiceName": "auto-benchmark-redis-service-fastapi"
     },
     "label": "Redis",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "auto-benchmark-kafka-cluster",
      "ServiceName": "auto-benchmark-kafka-service-fastapi"
     },
     "label": "Kafka",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Connections - PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "auto-benchmark-baseline-rds-pgdb"
     },
     "label": "Baseline",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "auto-benchmark-scale-rds-pgdb" },
     "label": "Scale",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "auto-benchmark-redis-rds-pgdb" },
     "label": "Redis",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "auto-benchmark-kafka-rds-pgdb" },
     "label": "Kafka",
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "CPU Utilization(%) - PostgreSQL",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "DBInstanceIdentifier": "auto-benchmark-baseline-rds-pgdb"
     },
     "label": "Baseline",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "auto-benchmark-scale-rds-pgdb" },
     "label": "Scale",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "auto-benchmark-redis-rds-pgdb" },
     "label": "Redis",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Maximum"
    },
    {
     "dimensions": { "DBInstanceIdentifier": "auto-benchmark-kafka-rds-pgdb" },
     "label": "Kafka",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Maximum"
    }
   ]
  },
  { "title": "ElastiCache - Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU Utilization(%) - Redis",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "auto-benchmark-redis-redis-001", "CacheNodeId": "0001" },
     "label": "Redis",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "auto-benchmark-kafka-redis-001", "CacheNodeId": "0001" },
     "label": "Kafka",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Cache Hit - Redis",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "auto-benchmark-redis-redis-001", "CacheNodeId": "0001" },
     "label": "Redis",
     "metricName": "CacheHitRate",
     "namespace": "AWS/ElastiCache",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "auto-benchmark-kafka-redis-001", "CacheNodeId": "0001" },
     "label": "Kafka",
     "metricName": "CacheHitRate",
     "namespace": "AWS/ElastiCache",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Average"
    }
   ]
  },
  { "title": "MSK - Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "CPU Utilization(%) - Kafka",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": { "Broker ID": "*", "Cluster Name": "auto-benchmark-kafka-msk" },
     "metricName": "CpuSystem",
     "namespace": "AWS/Kafka",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Client Connection - Kafka",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "Cluster Name": "auto-benchmark-kafka-msk" },
     "label": "Kafka",
     "metricName": "ClientConnectionCount",
     "namespace": "AWS/Kafka",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Task Count - Kafka-Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "auto-benchmark-kafka-cluster",
      "ServiceName": "auto-benchmark-kafka-service-consumer"
     },
     "label": "Consumer",
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "ECS/ContainerInsights", "type": "string" }, "type": "property" },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DesiredTaskCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "auto-benchmark-kafka-cluster" }, "property": { "name": "ClusterName", "type": "string" }, "type": "operator" },
        {
         "operator": {
          "name": "=",
          "value": "auto-benchmark-kafka-service-consumer"
         },
         "property": { "name": "ServiceName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DesiredTaskCount) FROM \"ECS/ContainerInsights\" WHERE ClusterName = 'auto-benchmark-kafka-cluster' AND ServiceName = 'auto-benchmark-kafka-service-consumer' ORDER BY SUM() ASC",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "auto-benchmark-kafka-cluster",
      "ServiceName": "auto-benchmark-kafka-service-redis-outbox"
     },
     "label": "Outbox",
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "period": "1s",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "ECS/ContainerInsights", "type": "string" }, "type": "property" },
      "orderBy": { "name": "SUM", "type": "function" },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DesiredTaskCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "auto-benchmark-kafka-cluster" }, "property": { "name": "ClusterName", "type": "string" }, "type": "operator" },
        {
         "operator": {
          "name": "=",
          "value": "auto-benchmark-kafka-service-consumer"
         },
         "property": { "name": "ServiceName", "type": "string" },
         "type": "operator"
        }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DesiredTaskCount) FROM \"ECS/ContainerInsights\" WHERE ClusterName = 'auto-benchmark-kafka-cluster' AND ServiceName = 'auto-benchmark-kafka-service-consumer' ORDER BY SUM() ASC",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Utilization(%) - Kafka-Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dimensions": {
      "ClusterName": "auto-benchmark-kafka-cluster",
      "ServiceName": "auto-benchmark-kafka-service-consumer"
     },
     "label": "Consumer",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "ClusterName": "auto-benchmark-kafka-cluster",
      "ServiceName": "auto-benchmark-kafka-service-redis-outbox"
     },
     "label": "Outbox",
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "queryLanguage": "CWLI",
     "queryMode": "Metrics",
     "region": "ca-central-1",
     "statistic": "Average"
    }
   ]
  }
 ]
}